### PR TITLE
Fix on pymodbus 3.7.x

### LINKED ISSUE #17: pymodbus.console do not start with version 3.7.0
When I try to start pymodbus.console I get the following error message:

ImportError: cannot import name 'ModbusBinaryFramer' from 'pymodbus.transaction' (/Users/sergiobruni/.pyenv/versions/3.12-dev/envs/panarea2/lib/python3.12/site-packages/pymodbus/transaction.py). Did you mean: 'ModbusAsciiFramer'?

### PR DESCRIPTION
**Pull request by alexrudd2**
Closes #17

I have not tested actual functionality, just confirmed that the client and server start without crashing.

### CODE REVIEW

**Review by janiversen — COMMENTED** [review]
This repo is @dhoomakethu, he wanted a separate repo so he could do the maintenance easier, so I will leave it to him.

**Comment by alexrudd2** [comment]
> This repo is @dhoomakethu, he wanted a separate repo so he could do the maintenance easier, so I will leave it to him.

Yes, I understand that.  I'm just requesting your review on this one to confirm I made the API changes right.  On the other changes he's the only reviewer :)

**Review by dhoomakethu — APPROVED** [review]

**Comment by dhoomakethu** [comment]
So does this mean, `pymodbus` no longer supports binary framer ?

**Comment by alexrudd2** [comment]
https://github.com/pymodbus-dev/pymodbus/pull/2130

**Comment by dhoomakethu** [comment]
@alexrudd2 I have added some more changes to be in line with pymodbus3.7, Refer MR #21 . JFYI

**Comment by alexrudd2** [comment]
Closing in favor of #21

**Pull request closed without merging**
