### PR TITLE
Add basic GitHub actions workflow

### PR DESCRIPTION
**Pull request by alexrudd2**
Progress towards #3.  This adds `ruff` ,`mypy`, and `pytest`.  (but doesn't do any fancy caching like #9)

Note this is based off the `ruff` branch because `main` currently has lint and type errors.

### CODE REVIEW

**Comment by alexrudd2** [comment]
> Does this supersede #19 ? I see similar changes here as well.

No, it simply includes those earlier commits because it's based off that branch.

**Comment by dhoomakethu** [comment]
@alexrudd2 , Are these jobs expected to fail?

**Comment by alexrudd2** [comment]
No, they were passing when I made the PR but something broke with poetry.  I'll look into it; should be an easy fix

**Comment by dhoomakethu** [comment]
closes #3

**Pull request merged**
